[project]
name = "limited-angle-ct-reconstruction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "astra-toolbox>=2.5.0",
    "inverse-problems-python",
    "matplotlib>=3.11.1",
    "numba>=0.67.0",
    "numpy>=2.4.6",
    "pillow>=12.3.0",
    "scikit-image>=0.26.0",
    "scipy>=1.17.1",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "tqdm>=4.70.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]

[tool.uv.sources]
inverse-problems-python = { git = "https://github.com/devangelista2/IPPy.git" }
